### ISSUE TITLE
Set not "ref: master." but "ref: master"

### ISSUE THREAD

**Issue by junaruga** [fedora-modularity/dependency-report-scripts#2]
```
$ mbs-build local
```

Checking log 

```
DEBUG: Executing command: ['sh', '-c', 'fedpkg clone --anonymous ruby; git -C ruby checkout master.']
...
DEBUG: error: pathspec 'master.' did not match any file(s) known to git.
```

"ref: master." is set in the file. "master." But it is not valid as branch name.
https://github.com/fedora-modularity/dependency-report/blob/master/modules/ruby/ruby.yaml

**Comment by nphilipp** [comment]
This should be fixed in commit c4123295c7308a4e28616ccaa1e4ef71411d7cc5, see pull request #1.
