### ISSUE TITLE
Using "- " not inline format "[]" for sequencing element

### ISSUE THREAD

**Issue by junaruga** [fedora-modularity/dependency-report-scripts#5]
The generated modulemd.yaml file is here.
https://github.com/fedora-modularity/dependency-report/blob/master/modules/ruby/ruby.yaml

My concern is 
The file is using inline format "[]" for sequencing element.

```
    license:
        module: [ MIT ]
```

But below specification document is using "- " for the sequencing element.
https://pagure.io/modulemd/blob/master/f/spec.yaml

```
    license:
        module:
            - MIT
```

So, I think it is better to generate "-" following the specification.

**Comment by contyk** [comment]
Both forms are perfectly valid YAML. It's a matter of personal taste.

**Comment by junaruga** [comment]
Yes, of course, both forms are perfectly valid YAML.

But which pattern do you prefer? which pattern do you want users to use as a modularity team?

**Comment by contyk** [comment]
I don't want to dictate that :) Everyone's free to use whichever style they prefer.

**Comment by junaruga** [comment]
OK I would close this ticket.
Thanks for the explanation.
